name: ML Workflow with CML
on: [push] 

jobs: 
  train-model:
    runs-on: self-hosted
    steps:
      - name: clone repo into ec2
        run: |
          cd /home/ubuntu/mlops1
          git clone https://github.com/SruthiKeerthana/MLOps.git          
          
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10' # Specify your desired Python version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          
      - name: Activate VE and Train the Model
        run: |
          source /home/ubuntu/mlflow/pyvenvs/mlopstest1/bin/activate 
          make run_pipeline
